"""Surveyor — monitors pipeline execution and persists observability signals.

Lifecycle (called from CLI):

    surveyor = Surveyor(manifest, store_dir=Path(".aqueduct"), webhook_url=...)
    surveyor.start(run_id)          # create DB tables, record run start
    result = execute(manifest, spark, run_id=run_id)
    failure_ctx = surveyor.record(result)   # persist result, fire webhook if failed
    surveyor.stop()                 # close DB connection

DuckDB schema
─────────────
  run_records        — one row per run (start + final status)
  failure_contexts   — one row per failed run (FailureContext document)

Phase 5 scope: logging + webhook only.  LLM patch loop wired in Phase 7.
"""

from __future__ import annotations

import json
import traceback
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import logging

import duckdb

from aqueduct.compiler.models import Manifest
from aqueduct.executor.models import ExecutionResult
from aqueduct.surveyor.models import FailureContext, RunRecord
from aqueduct.surveyor.webhook import fire_webhook

logger = logging.getLogger(__name__)

# ── DDL ───────────────────────────────────────────────────────────────────────

_DDL = """
CREATE TABLE IF NOT EXISTS run_records (
    run_id       VARCHAR PRIMARY KEY,
    pipeline_id  VARCHAR NOT NULL,
    status       VARCHAR NOT NULL,
    started_at   TIMESTAMPTZ NOT NULL,
    finished_at  TIMESTAMPTZ,
    module_results JSON
);

CREATE TABLE IF NOT EXISTS failure_contexts (
    run_id         VARCHAR PRIMARY KEY,
    pipeline_id    VARCHAR NOT NULL,
    failed_module  VARCHAR NOT NULL,
    error_message  VARCHAR NOT NULL,
    stack_trace    VARCHAR,
    manifest_json  JSON,
    started_at     TIMESTAMPTZ NOT NULL,
    finished_at    TIMESTAMPTZ NOT NULL
);
"""

# ── Helpers ───────────────────────────────────────────────────────────────────

def _utcnow() -> datetime:
    return datetime.now(tz=timezone.utc)


def _iso(dt: datetime) -> str:
    return dt.isoformat()


def _first_failed_module(result: ExecutionResult) -> str:
    """Return the module_id of the first failing module, or '_executor'."""
    for mr in result.module_results:
        if mr.status == "error":
            return mr.module_id
    return "_executor"


def _first_error_message(result: ExecutionResult, exc: Exception | None) -> str:
    for mr in result.module_results:
        if mr.status == "error" and mr.error:
            return mr.error
    if exc is not None:
        return str(exc)
    return "unknown error"


# ── Public API ────────────────────────────────────────────────────────────────

class Surveyor:
    """Observability recorder for a single pipeline instance.

    One Surveyor per ``aqueduct run`` invocation.  Not thread-safe itself —
    the webhook is fire-and-forget in a daemon thread; everything else is
    single-threaded.
    """

    def __init__(
        self,
        manifest: Manifest,
        store_dir: Path,
        webhook_url: str | None = None,
        webhook_config: "WebhookEndpointConfig | None" = None,  # type: ignore[name-defined]  # noqa: F821
        blueprint_path: Path | None = None,
        patches_dir: Path | None = None,
    ) -> None:
        from aqueduct.config import WebhookEndpointConfig
        self._manifest = manifest
        self._store_dir = store_dir
        if webhook_config is not None:
            self._webhook_config: WebhookEndpointConfig | None = webhook_config
        elif webhook_url is not None:
            self._webhook_config = WebhookEndpointConfig(url=webhook_url)
        else:
            self._webhook_config = None
        self._blueprint_path = blueprint_path
        self._patches_dir = patches_dir or Path("patches")
        self._run_id: str | None = None
        self._started_at: datetime | None = None
        self._conn: duckdb.DuckDBPyConnection | None = None

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    def start(self, run_id: str) -> None:
        """Open the DuckDB store and record run start.

        Creates ``.aqueduct/runs.db`` (and parent dirs) if they do not exist.

        Args:
            run_id: The UUID generated by the CLI / Executor for this run.
        """
        self._run_id = run_id
        self._started_at = _utcnow()
        self._store_dir.mkdir(parents=True, exist_ok=True)

        db_path = self._store_dir / "runs.db"
        self._conn = duckdb.connect(str(db_path))
        self._conn.execute(_DDL)

        self._conn.execute(
            """
            INSERT OR REPLACE INTO run_records
                (run_id, pipeline_id, status, started_at, finished_at, module_results)
            VALUES (?, ?, 'running', ?, NULL, '[]')
            """,
            [run_id, self._manifest.pipeline_id, _iso(self._started_at)],
        )

    def record(
        self,
        result: ExecutionResult,
        exc: Exception | None = None,
    ) -> FailureContext | None:
        """Persist the final run outcome.

        Updates the ``run_records`` row to its terminal status.  On failure,
        also inserts a ``failure_contexts`` row and (if configured) fires a
        webhook in a daemon thread.

        Args:
            result: ``ExecutionResult`` from the Executor.
            exc:    Optional unhandled ``ExecuteError`` that escaped execute().
                    Used to populate ``stack_trace`` when the exception was not
                    caught inside the Executor loop.

        Returns:
            ``FailureContext`` if the run failed, else ``None``.
        """
        if self._conn is None or self._run_id is None:
            raise RuntimeError("Surveyor.start() must be called before record()")

        finished_at = _utcnow()
        module_results_json = json.dumps(
            [{"module_id": r.module_id, "status": r.status, "error": r.error}
             for r in result.module_results]
        )

        self._conn.execute(
            """
            UPDATE run_records
            SET status = ?, finished_at = ?, module_results = ?
            WHERE run_id = ?
            """,
            [result.status, _iso(finished_at), module_results_json, result.run_id],
        )

        if result.status == "success":
            return None

        # ── Build FailureContext ───────────────────────────────────────────────
        stack_trace: str | None = None
        if exc is not None:
            stack_trace = "".join(traceback.format_exception(type(exc), exc, exc.__traceback__))

        ctx = FailureContext(
            run_id=result.run_id,
            pipeline_id=self._manifest.pipeline_id,
            failed_module=_first_failed_module(result),
            error_message=_first_error_message(result, exc),
            stack_trace=stack_trace,
            manifest_json=json.dumps(self._manifest.to_dict()),
            started_at=_iso(self._started_at),  # type: ignore[arg-type]
            finished_at=_iso(finished_at),
        )

        self._conn.execute(
            """
            INSERT OR REPLACE INTO failure_contexts
                (run_id, pipeline_id, failed_module, error_message,
                 stack_trace, manifest_json, started_at, finished_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            [
                ctx.run_id,
                ctx.pipeline_id,
                ctx.failed_module,
                ctx.error_message,
                ctx.stack_trace,
                ctx.manifest_json,
                ctx.started_at,
                ctx.finished_at,
            ],
        )

        if self._webhook_config:
            attempt = sum(1 for mr in result.module_results if mr.status == "error")
            template_vars = {
                "run_id": ctx.run_id,
                "pipeline_id": ctx.pipeline_id,
                "pipeline_name": self._manifest.name,
                "failed_module": ctx.failed_module,
                "error_message": ctx.error_message,
                "error_type": (ctx.stack_trace or "").splitlines()[0] if ctx.stack_trace else "ExecuteError",
                "started_at": ctx.started_at,
                "attempt": str(attempt),
            }
            fire_webhook(self._webhook_config, ctx.to_dict(), template_vars)

        return ctx

    def evaluate_regulator(self, regulator_id: str) -> bool:
        """Evaluate whether a Regulator's gate is open (True) or closed (False).

        Finds the Probe wired to the Regulator via a signal-port edge, queries
        the latest ``passed`` field from its signals in the current run, and
        applies boolean coercion per spec:

          - ``passed=True`` or key absent or no signals → open (True)
          - ``passed=False``                            → closed (False)
          - any exception                               → open (True)

        Args:
            regulator_id: Module ID of the active Regulator to evaluate.

        Returns:
            True if the gate is open (downstream should execute).
            False if the gate is closed (on_block applies).
        """
        if self._run_id is None:
            return True  # start() not called

        # Find the probe wired to this regulator's signal port
        probe_ids = [
            e.from_id
            for e in self._manifest.edges
            if e.to_id == regulator_id and e.port == "signal"
        ]
        if not probe_ids:
            return True  # no signal source → open

        probe_id = probe_ids[0]

        signals_db = self._store_dir / "signals.db"
        if not signals_db.exists():
            return True  # no signals written → open

        try:
            conn = duckdb.connect(str(signals_db))
            try:
                rows = conn.execute(
                    """
                    SELECT payload
                    FROM probe_signals
                    WHERE probe_id = ? AND run_id = ?
                    ORDER BY captured_at DESC
                    """,
                    [probe_id, self._run_id],
                ).fetchall()
            finally:
                conn.close()

            # Walk rows newest-first, look for first payload containing 'passed'
            for (payload_raw,) in rows:
                payload = json.loads(payload_raw) if isinstance(payload_raw, str) else payload_raw
                if isinstance(payload, dict) and "passed" in payload:
                    passed = payload["passed"]
                    if passed is None:
                        return True
                    return bool(passed)

            return True  # no signal with 'passed' key → open

        except Exception:
            return True  # error → open per spec

    def get_probe_signal(
        self,
        probe_id: str,
        signal_type: str | None = None,
    ) -> list[dict]:
        """Return probe signal payloads for a given probe.

        Opens a fresh read connection to ``store_dir/signals.db``.  Returns
        an empty list if the signals DB does not exist yet.

        Args:
            probe_id:    The Probe module ID to query.
            signal_type: Optional filter — if given, only rows of that type
                         are returned.

        Returns:
            List of dicts: ``{"run_id", "probe_id", "signal_type", "payload",
            "captured_at"}``.  ``payload`` is already deserialised (dict).
        """
        import json as _json

        import duckdb as _duckdb

        signals_db = self._store_dir / "signals.db"
        if not signals_db.exists():
            return []

        conn = _duckdb.connect(str(signals_db))
        try:
            if signal_type is not None:
                rows = conn.execute(
                    """
                    SELECT run_id, probe_id, signal_type, payload,
                           CAST(captured_at AS VARCHAR) AS captured_at
                    FROM probe_signals
                    WHERE probe_id = ? AND signal_type = ?
                    ORDER BY captured_at DESC
                    """,
                    [probe_id, signal_type],
                ).fetchall()
            else:
                rows = conn.execute(
                    """
                    SELECT run_id, probe_id, signal_type, payload,
                           CAST(captured_at AS VARCHAR) AS captured_at
                    FROM probe_signals
                    WHERE probe_id = ?
                    ORDER BY captured_at DESC
                    """,
                    [probe_id],
                ).fetchall()
        finally:
            conn.close()

        return [
            {
                "run_id": r[0],
                "probe_id": r[1],
                "signal_type": r[2],
                "payload": _json.loads(r[3]) if isinstance(r[3], str) else r[3],
                "captured_at": str(r[4]),
            }
            for r in rows
        ]

    def stop(self) -> None:
        """Close the DuckDB connection."""
        if self._conn is not None:
            self._conn.close()
            self._conn = None
