"""The capability walker must derive the SAME leaf set on every Python version.

The closure test's whole premise — "the walker (code) and the YAML (data) are
two INDEPENDENT sources, so they can actually disagree" — is only meaningful if
the walker's output is deterministic. It is NOT deterministic if it depends on
the interpreter: a table generated by ``aqueduct dev capabilities scaffold`` on
one Python then fails ``load_declaration()`` on another, and because
``deployment.engine`` validation is fail-closed, that breaks every
``aqueduct.yml`` load on the interpreters where the walker under-derives.

That is exactly what happened: ``config_leaves._direct_basemodel`` matched only
``origin is typing.Union``. A PEP 604 annotation (``Sub | None`` — how
``aqueduct/config.py`` writes its optional sub-config fields) reports origin
``types.UnionType`` on Python 3.11-3.13 and only unifies to ``typing.Union`` on
3.14. So on the entire supported range below 3.14 every ``Sub | None`` field
failed to unwrap and its children were never derived — 41 fewer config leaves
(60 vs 101) — while the committed ``capabilities.yml`` (scaffolded on 3.14)
listed those children, making them orphan rows that failed registration for the
SHIPPED Spark engine.

These tests fail on the pre-fix code when run on Python < 3.14, and pass on
every interpreter after the fix.
"""

from __future__ import annotations

from typing import Optional, Union  # noqa: UP035 — pre-604 spellings tested deliberately

import pytest
from pydantic import BaseModel

from aqueduct.executor.config_leaves import leaves_for_model

pytestmark = pytest.mark.unit


class _Inner(BaseModel):
    a: int = 1
    b: str = "x"


class _OuterPep604(BaseModel):
    """A model whose sub-config field uses the PEP 604 ``Inner | None`` spelling
    — identical to how ``aqueduct/config.py`` declares ``agent.budget``,
    ``deployment.databricks``, etc."""

    inner: _Inner | None = None
    top: int = 0


class _OuterOptional(BaseModel):
    """Same shape via ``typing.Optional[Inner]`` / ``typing.Union[Inner, None]``
    — must derive the SAME leaves, because it is the SAME type. Uses the
    ``typing`` spellings (origin ``typing.Union`` on every version) that the
    pre-fix walker handled, to prove the two spellings now agree."""

    inner: Optional[_Inner] = None  # noqa: UP045 — deliberately the pre-604 spelling
    top: int = 0


class _OuterUnion(BaseModel):
    inner: Union[_Inner, None] = None  # noqa: UP007 — deliberately the pre-604 spelling
    top: int = 0


def test_pep604_optional_submodel_is_recursed_not_atomic():
    """A ``Inner | None`` field yields its CHILDREN, not one atomic parent leaf.

    On the pre-fix walker running on Python < 3.14, ``get_origin(Inner | None)``
    is ``types.UnionType`` (not ``typing.Union``), so the union never unwraps
    and this asserts False — ``config.inner`` would be the only leaf. This is
    the regression guard for the framework bug that broke Spark registration on
    3.11-3.13.
    """
    leaves = leaves_for_model(_OuterPep604)
    assert leaves == {"config.inner.a", "config.inner.b", "config.top"}


def test_pep604_and_typing_optional_agree():
    """``Inner | None``, ``Optional[Inner]``, and ``Union[Inner, None]`` are the
    same type and MUST derive the same leaf set — the walker cannot be sensitive
    to which spelling the schema author used (or, equivalently, to the Python
    version, since only the PEP 604 spelling's origin changed across versions)."""
    pep604 = leaves_for_model(_OuterPep604)
    assert pep604 == leaves_for_model(_OuterOptional)
    assert pep604 == leaves_for_model(_OuterUnion)


def test_real_config_optional_submodel_leaves_present():
    """The real symptom, pinned against the actual schema: ``agent.budget`` is
    ``AgentBudgetConfig | None`` in ``aqueduct/config.py``, so its sub-leaves
    must be derived on every interpreter. Their ABSENCE is what orphaned the
    committed ``capabilities.yml`` rows and failed Spark registration below
    3.14."""
    from aqueduct.executor.config_leaves import all_config_leaves

    leaves = all_config_leaves()
    # A sub-leaf reached only through the `agent.budget: AgentBudgetConfig | None`
    # PEP 604 union — the exact leaf named in the CapabilityDeclarationError.
    assert "config.agent.budget.max_reprompts" in leaves
    # And the parent must NOT survive as an atomic leaf (that was the buggy shape).
    assert "config.agent.budget" not in leaves


def test_registered_engine_tables_match_walker_on_this_interpreter():
    """End-to-end determinism proof: every registered engine's committed YAML
    loads cleanly against the walker-derived leaf set ON THE CURRENT PYTHON.

    This is the assertion that fails on 3.11-3.13 pre-fix (the shipped Spark
    ``capabilities.yml`` names leaves the under-derived walker does not produce,
    so ``load_engines()`` raises ``CapabilityDeclarationError``). Running the
    capability suite on more than one interpreter in CI (see
    ``.github/workflows`` compat matrix) is what turns this into a real
    cross-version guarantee rather than a dev-interpreter accident.
    """
    from aqueduct.executor.capabilities import CAPABILITY_REGISTRY, load_engines

    load_engines()  # raises CapabilityDeclarationError if any table disagrees with the walker
    assert "spark" in CAPABILITY_REGISTRY
