"""Synthetic cross-engine handoff module insertion (Phase 81 Step 2).

Step 1 (`aqueduct/compiler/islands.py`) derives engine islands and the
BOUNDARY EDGES between them, but only validates them — it does not
synthesize anything. This module is the next stage: at each boundary edge
`A -> B` (differing resolved engines on either endpoint), the compiler
splices in a synthetic HANDOFF module: `A -> B` becomes `A -> handoff ->
B`. Every non-boundary edge is left untouched.

**This is compile-time synthesis only.** The handoff module's `config`
carries the TRANSPORT CONTRACT (below) — everything the Step 3 executor
needs to actually perform the write and the read — but no engine-side I/O
happens here. No SparkSession/DuckDB connection is touched, and no
directory is created.

**V1 transport contract.** An engine-native parquet write to a URI: the
upstream island materializes its output (`df.write.parquet` on Spark,
`COPY ... TO ... (FORMAT PARQUET)` on DuckDB), the downstream island reads
it back. Parquet is a FIXED internal transport detail — deliberately not a
config key; there is no format knob. The spill location itself is a
runtime concern the Step 3 executor resolves from `aqueduct.yml`'s
`handoff.root` (`aqueduct.config.HandoffConfig`) plus the manifest hash and
run id it already computes/receives — layout is
`<root>/<manifest_hash>/<run_id>/<edge_id>/`, where `edge_id` is the ONE
piece of that template only the compiler can supply (it names WHICH
boundary), carried in the handoff module's own `config["edge_id"]` (equal
to its own module id, generated by `_handoff_id` below).

A handoff module's `config` dict:

    {
        "edge_id": "<handoff module's own id>",
        "from_module": "<upstream module id>",
        "to_module": "<downstream module id>",
        "from_engine": "<engine name>",
        "to_engine": "<engine name>",
        "port": "<original boundary edge's port — always 'main' in v1,
                  since a cross-island spillway edge is already a
                  CompileError before this module ever runs>",
    }

**Not user-writable.** `ModuleType.Handoff` is excluded from
`aqueduct.parser.schema.VALID_MODULE_TYPES`, and `ModuleSchema.validate_type`
rejects it with a dedicated message — a Blueprint can never parse one into
existence. Every handoff `Module` this function builds also carries
`synthetic=True` (mirrors `Edge.injected`), the general "compiler
inserted this, not the author" marker.

**Capability gate interaction.** A handoff module's id is deliberately
NEVER a member of any `Island.module_ids` (islands are derived from the
ORIGINAL pre-insertion module graph — see `islands.py` — and this function
runs strictly after that). `aqueduct/compiler/compiler.py`'s per-island
capability-gate loop filters `manifest.modules` down to each island's
`module_ids`, so a handoff module is structurally excluded from every
island's check — the same "falls out free" property Step 1's disjoint-
component case has. `module.type.Handoff` is still a governed capability
leaf (every `ModuleType` member is, automatically), declared `unsupported`
on both shipped engines today — that verdict is honest (no engine has a
real per-engine transport handler yet; Step 3 adds one and revisits it)
and inert (the gate never actually asks the question against a real
compiled Manifest, for the reason above).

**Lineage passthrough.** `aqueduct/compiler/lineage.py::compute_lineage_rows`
emits one wildcard passthrough row per handoff module (columns cross the
boundary unchanged) — the same `_opaque_row` convention already used for a
Channel lineage can't resolve column-by-column.
"""

from __future__ import annotations

from dataclasses import dataclass

from aqueduct.compiler.islands import BoundaryEdge
from aqueduct.parser.models import Edge, Module, ModuleType

# Compile-time warning naming each handoff point — see compiler.py, which
# emits this through the existing `aqueduct.warnings.emit` machinery (never
# a bare print), same mechanism as `capability_check.RULE_ID_IGNORED` /
# `RULE_ID_CROSS_ENGINE_HEAL`.
RULE_ID_CROSS_ENGINE_HANDOFF = "cross_engine_handoff_io"


@dataclass(frozen=True)
class HandoffInsertion:
    """One synthesized handoff module + the boundary edge it bridges.

    Returned alongside the rewired module/edge lists so the caller
    (`compiler.compile()`) can emit the `cross_engine_handoff_io` warning
    without re-deriving anything.
    """

    module: Module
    boundary: BoundaryEdge


def _handoff_id(from_id: str, to_id: str, existing_ids: set[str]) -> str:
    """Generate a collision-proof id for a handoff module.

    User module ids may never contain `__` (`parser.schema.ModuleSchema`'s
    `validate_id` rejects it — reserved for Arcade namespacing), so any id
    built from `__`-joined segments cannot collide with an authored id by
    construction. The numeric-suffix loop is defense in depth for the
    (already-unreachable in practice) case of two boundary edges sharing
    the same endpoints.
    """
    base = f"{from_id}__handoff__{to_id}"
    candidate = base
    n = 2
    while candidate in existing_ids:
        candidate = f"{base}__{n}"
        n += 1
    return candidate


def insert_handoff_modules(
    modules: list[Module],
    edges: list[Edge],
    boundaries: list[BoundaryEdge],
) -> tuple[list[Module], list[Edge], list[HandoffInsertion]]:
    """Insert one synthetic Handoff module per boundary edge.

    `A -> B` (a boundary edge) becomes `A -> handoff -> B`: the original
    edge is replaced by two edges carrying the SAME port, preserving edge
    semantics exactly (no port/error_types loss). Every non-boundary edge
    is returned unchanged, in its original position.

    Zero boundaries (disjoint components on different engines produce
    none — no edge connects them at all; a single-engine Blueprint has
    exactly one island and therefore no boundary edges either) returns the
    INPUT objects unchanged — byte-identical output, no allocation.
    """
    if not boundaries:
        return modules, edges, []

    existing_ids = {m.id for m in modules}
    boundary_by_edge: dict[Edge, BoundaryEdge] = {b.edge: b for b in boundaries}

    new_modules: list[Module] = list(modules)
    new_edges: list[Edge] = []
    insertions: list[HandoffInsertion] = []

    for e in edges:
        boundary = boundary_by_edge.get(e)
        if boundary is None:
            new_edges.append(e)
            continue

        handoff_id = _handoff_id(e.from_id, e.to_id, existing_ids)
        existing_ids.add(handoff_id)
        handoff_module = Module(
            id=handoff_id,
            type=ModuleType.Handoff,
            label=f"Cross-engine handoff: {e.from_id} → {e.to_id}",
            config={
                "edge_id": handoff_id,
                "from_module": e.from_id,
                "to_module": e.to_id,
                "from_engine": boundary.from_engine,
                "to_engine": boundary.to_engine,
                "port": e.port,
            },
            synthetic=True,
        )
        new_modules.append(handoff_module)
        new_edges.append(Edge(from_id=e.from_id, to_id=handoff_id, port=e.port))
        new_edges.append(Edge(from_id=handoff_id, to_id=e.to_id, port=e.port))
        insertions.append(HandoffInsertion(module=handoff_module, boundary=boundary))

    return new_modules, new_edges, insertions


__all__ = [
    "RULE_ID_CROSS_ENGINE_HANDOFF",
    "HandoffInsertion",
    "insert_handoff_modules",
]
